---
title: "Building html pages from bibtex"
author: "Steve Simon"
output: html_document
---

This program was written in R Markdown by Steve Simon. It was created on 2019-06-11 and last updated on `r Sys.Date()`.


```{r echo=FALSE}
source(file="prelims.R", echo=FALSE)
suppressMessages(suppressWarnings(library(tidyverse)))
knitr::opts_chunk$set(echo=FALSE)
verbose <- TRUE
```

```{r read-bib}
bib_path <- "../data/19/06"
md_path <- "../md"
web_path <- "../website"
bib_files <- list.files(path=bib_path, pattern="*.bib")
```

```{r extract-fields}

index_page <- build_index_yaml()
for (f in bib_files) {
  txt_full <- readLines(paste0(bib_path, "/", f))
  short_name <- select_name(txt_full)[2]
  md_path %>%
    paste0("/") %>%
    paste0(short_name) %>%
    paste0(".Rmd") -> long_name
  if (verbose) {cat(short_name); cat("\n\n")}
  yaml_header <- build_yaml_header(txt_full)
  image_link <- build_image_link(f)
  document_link <- build_document_link(txt_full)
  citation <- build_citation(txt_full)
  write(yaml_header, long_name, append=FALSE)
  write(image_link, long_name, append=TRUE)
  write(document_link, long_name, append=TRUE)
  write(citation, long_name, append=TRUE)
  index_page %>%
    paste0("[") %>%
    paste0(short_name) %>%
    paste0("](") %>%
    paste0(short_name) %>%
    paste0(".html)") %>%
    add_line_breaks(2) -> index_page
}
write(index_page, paste0(md_path, '/index.Rmd'))
file_list <- list.files(path=md_path, pattern="*.Rmd", full.names=TRUE)
for (f in file_list) {
  render(f, output_dir=web_path)
}
```

```{r build-citation}

divider <- paste0(rep("=", 50), collapse="")
```

