---
title: "Add headers to md files"
author: "Steve Simon"
date: "6/28/2019"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo=FALSE)
source(file="prelims.R", echo=FALSE)
verbose <- TRUE
```


```{r list-dirs}
b2_path <- "c:/Users/steve/Dropbox/professional/web/b2"
b3_path <- "c:/Users/steve/Dropbox/professional/web/b3"
b2_names <- list.files(b2_path)
if (verbose) print(b2_names)
```

```{r read-md}
excluded_files <- "feed.md"
more_tag <- "\n\n<!---More--->"
b2_path                              %s%
  b2_names                           -> old_files
b3_path                              %s%
  b2_names                           -> new_files
n_files <- length(old_files)
for (i_file in 1:n_files) {
  if (b2_names[i_file] %in% excluded_files) next
  md_text <- readLines(old_files[i_file], warn=FALSE)
  title_line <- grep('::: {#content role="main"}', md_text, fixed=TRUE)+1
  md_text[title_line] %>% remove_ch(" \\{.*") -> md_title
  if (verbose) cat("\n"); cat(b2_names[i_file])
  body0 <- grep('::: {.entry-content}', md_text, fixed=TRUE)+1
  body1 <- grep(":::", md_text[-(1:body0)])
  body1 <- min(body1[body1>=body0])
  md_body <- paste0(md_text[body0:body1], collapse="\n")
  md_body <- sub("\\[\\]\\{.*?\\}", more_tag, md_body)
  category0 <- grep('This entry was posted in', md_text, fixed=TRUE)
  category1 <- grep('### Post navigation', md_text, fixed=TRUE)-1
  if (length(category0) != 1) next
  details <- paste0(md_text[category0:category1], collapse=" ")
  details %>%
    remove_ch("^.*posted in \\[") %>%
    remove_ch("\\].*") -> md_category
  details %>%
    remove_ch("^.*\\) on \\[") %>%
    remove_ch("\\].*") %>%
    mdy  %>%
    format("%Y-%m-%d") -> md_date
  i_tag <- regexpr("\\) and tagged \\[", details)
  j_tag <- regexpr("\\) on \\[", details)+1
  if (i_tag==-1) i_tag=j_tag-1
  details %>%
    substr(i_tag+13, j_tag-1) %>%
    remove_ch("\\(.*?\\)") %>%
    remove_ch("\\[") %>%
    remove_ch("\\]") -> md_tag
  if (i_tag > j_tag) md_tag <- Untagged
  if (verbose) {
    cat(", ")
    cat(md_title)
    cat("\n")
    cat(details)
    cat("\n")
    cat(md_category)
    cat("\n")
    cat(md_date)
    cat("\n")
    cat(md_tag)
    cat("\n")
  }
  yaml_header                          %1%
    "title: "    %q% md_title          %1%
    "author: "   %0% "Steve Simon"     %1%
    "date: "     %q% md_date           %1%
    "category: " %0% md_category       %1%
    "tags: "     %0% md_tag            %1%
    "output: "   %0% "html_document"   %1%
    yaml_header                        %2%
    
    md_body                            -> md_revised
  writeLines(md_revised, new_files[i_file])
}
```



```{r save-everything}
save.image("../data/create-b3.RData")
```