---
title: "Add headers to md files"
author: "Steve Simon"
date: "6/28/2019"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo=TRUE)
knitr::opts_chunk$set(error=TRUE)
source(file="prelims.R", echo=FALSE)
verbose <- TRUE
```

## Step 1. Find the .bib files

```{r list-dirs}
bib_names <- NULL
r1_names <- NULL
r1_root <- "c:/Users/steve/Dropbox/professional/web/r1/19"
for (i_month in c("05", "06", "07", "10", "11", "12")) {
  r1_path <- r1_root %s% i_month
  f0 <- list.files(path=r1_path, pattern="*.nbib")
  f1 <- list.files(path=r1_path, pattern="*.bib")
  fn <- setdiff(f1, f0)
  r1_names %<>% append(fn)
  bib_names %<>% append(r1_path %s% fn)
}
if (verbose) print(r1_names)
n_names <- length(r1_names)
r3_path <- "c:/Users/steve/Dropbox/professional/web/r3"
```

## Step 2. Read each .bib file and convert to .md file

First, set up the general structure.

```{r structure}
yaml_divider <- '---'
marks <- c(
  "title = ",
  "urldate = ",
  "mendeley-tags = ",
  "annote = ",
  "url = ",
  "pdf = ",
  "@"
)
default_marks <- c(
  "No title",
  "1999-09-09",
  "Untagged",
  "No commentary",
  "No html link",
  "No PDF link",
  "No short name"
)
n_marks <- length(marks)
```

Create bib_info, a matrix of information about the individual .bib files.

```{r create-info}
bib_cats <- c(
  "ttl",
  "dat",
  "tag",
  "not",
  "url",
  "pdf",
  "nam",
  "png"
)
n_cats <- length(bib_cats)
bib_info <- matrix("<<empty>>", nrow=n_names, ncol=n_cats)
dimnames(bib_info)[[2]] <- bib_cats
```

Populate bib_info

```{r bib-functions}

read_bib <- function(fn) {readLines(r1_path %s% r1_names[i_file])}

select_txt <- function(txt, lab, def) {
  txt %>% 
    gsub("{{", "{", .    , fixed=TRUE) %>%          # double bracket
    gsub(" {", "{", .    , fixed=TRUE) %>%          # leading blank
    gsub(" =", "=", .    , fixed=TRUE) %>%          # leading blank
    gsub("= ", "=", .    , fixed=TRUE) %>%          # trailing blank
    grep(lab, ., value=TRUE) -> lin 
  if (length(lin) == 0) {
    if (verbose) {cat(",", def)}
    return(def)
  }
  lin %>%
    remove_ch('article{'       , fixed=TRUE) %>%
    remove_ch('book{'          , fixed=TRUE) %>%
    remove_ch('inproceedings{' , fixed=TRUE) %>%
    remove_ch('misc{'          , fixed=TRUE) %>%
    remove_ch(',.*?$'          , fixed=TRUE) %>%          # from comma to end
    remove_ch('"'              , fixed=TRUE) %>%          # quote marks
    remove_ch('^\\s*'                      ) %>%          # trailing spaces
    remove_ch("^" %0% lab                  ) %>%          # label
    remove_ch('^\\{'                       ) %>%          # left curly bracket
    remove_ch('\\}'                        ) %>%          # right curly bracket
    remove_ch('\\s*$'                      ) %>%          # trailing blanks
    remove_ch(',$'                         ) -> selection # trailing comma
  if (is.null(selection)) return("")
  return(paste0(selection, collapse="; "))
}

```


```{r read-bib}
txt_original <- as.list(1:n_names)
for (i_file in 1:n_names) {
  if (verbose) {cat("\n", r1_names[i_file], sep="")}
  tx <- readLines(bib_names[i_file])
  txt_original[[i_file]]  <- tx

  bib_info[i_file, "ttl"] <- select_txt(tx, "title="        , "No title")
  bib_info[i_file, "dat"] <- select_txt(tx, "urldate="      , "No date")
  bib_info[i_file, "tag"] <- select_txt(tx, "mendeley-tags=", "No tags")
  bib_info[i_file, "not"] <- select_txt(tx, "annote="       , "No notes")
  bib_info[i_file, "url"] <- select_txt(tx, "url="          , "No html")
  bib_info[i_file, "pdf"] <- select_txt(tx, "pdf="          , "No pdf")
  bib_info[i_file, "nam"] <- select_txt(tx, "@"             , "No name")
  
  bib_info[i_file, "png"] <- r1_path %s% sub("bib$", "png", r1_names[i_file])

}
```

```{r build-md}
for (i_file in 1:n_names) {
  yaml_divider                                               %1%
    'title: '                    %q% bib_info[i_file, "ttl"] %1%
    'author: '                   %q% "Steve Simon"           %1%
    'date: '                     %q% bib_info[i_file, "dat"] %1%
    'category: '                 %0% 'Recommended'           %1%
    'tags: '                     %q% bib_info[i_file, "tag"] %1%
    'output: '                   %0% 'html_document'         %1%
    yaml_divider                                             %2%

    bib_info[i_file, "not"]                                  %2%
    
    '<!---More--->'                                          %2%
    
    '![]'                        %p% bib_info[i_file, "png"] %2%
    
    'Available in [html format]' %p% bib_info[i_file, "url"] %0%
    ' or [PDF format]'           %p% bib_info[i_file, "pdf"] %0%
    '.\n'                                                    -> md_file
  
  md_file %>%
    sub(" or [PDF format](No pdf)",  "", ., fixed=TRUE)  %>%
    sub(" [html format](No html) or", "", ., fixed=TRUE) -> md_file
  new_name <- r3_path %s% bib_info[i_file, "nam"] %0% ".md"
  if (verbose) {"Writing" %b% cat(new_name %b% ".\n")}
  writeLines(md_file, new_name)
}
```

## Step 3. Produce an index

```{r produce-index, eval=FALSE} 
o <- rev(order(bib_dates))
bib_dates <- bib_dates[o]
bib_names <- bib_names[o]
txt_full <- as.list(1:bib_count)
for (i in 1:bib_count) {
  txt_full[[i]] <- txt_original[[o[i]]]
}
```

## Step 4. Add a footer

## Step 5. Convert to html

## Step 6. List incomplete areas

```{r incomplete}
bib_df <- data.frame(bib_info, stringsAsFactors=FALSE)
bib_df %>%
  filter(tag=="No tags") %>%
  mutate(png=substr(png, 47, 99)) %>%
  mutate(png=sub(".png", "", png)) %>%
  select(tag, png)
bib_df %>%
  filter(tag=="") %>%
  mutate(png=substr(png, 47, 99)) %>%
  mutate(png=sub(".png", "", png)) %>%
  select(tag, png)
```


Save everything.

```{r save-everything}
save.image("../data/create-r3.RData")
```